# Generated by Django 2.0.6 on 2018-06-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(db_index=True, help_text='Opción de decarga [Nombre o RUN]', max_length=256)),
                ('rut', models.CharField(db_index=True, help_text='RUN en caso de tenerlo', max_length=256)),
                ('dniID', models.CharField(db_index=True, help_text='Número de Pasaporte', max_length=256)),
                ('names', models.CharField(db_index=True, help_text='Nombres [Escribir como aparece en documento de identidad]', max_length=256)),
                ('surname1', models.CharField(db_index=True, help_text='Apellido paterno', max_length=256)),
                ('surname2', models.CharField(db_index=True, help_text='Apellido materno', max_length=256)),
                ('fechaNas', models.DateField(db_index=True, help_text='Fecha de nacimiento')),
                ('idPaisOrigen', models.CharField(db_index=True, help_text='País de origen', max_length=256)),
                ('email', models.EmailField(db_index=True, max_length=256)),
            ],
        ),
    ]
