# Generated by Django 2.0.6 on 2018-06-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='active',
            field=models.BooleanField(default=True, help_text='Indica si esta en proceso activo'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email donde será notificado', max_length=256),
        ),
    ]
