# Generated by Django 2.0.6 on 2018-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_auto_20180621_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='dniID',
            field=models.CharField(blank=True, db_index=True, help_text='Número de Pasaporte', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email donde será notificado', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='fechaNas',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='idPaisOrigen',
            field=models.CharField(blank=True, db_index=True, help_text='País de origen', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='names',
            field=models.CharField(blank=True, db_index=True, help_text='Nombres [Escribir como aparece en documento de identidad]', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='rut',
            field=models.CharField(blank=True, db_index=True, help_text='RUN en caso de tenerlo', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='surname1',
            field=models.CharField(blank=True, db_index=True, help_text='Apellido paterno', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='surname2',
            field=models.CharField(blank=True, db_index=True, help_text='Apellido materno', max_length=256, null=True),
        ),
    ]
